### ISSUE TITLE
Missing util/arduino-electron-fixes.h

### ISSUE THREAD

**Issue by AaronInLA** [peergum/ModbusMaster-Electron#1]
More likely that I am missing something, but it's not clear to me where to find this file.

**Comment by peergum** [comment]
Sorry I forgot the util folder. Will add asap

**Comment by peergum** [comment]
Fixed.

**Comment by AaronInLA** [comment]
I'm sure this isn't the right venue for this - but I wanted to thank you for your help... it's been really useful and I really appreciate it. 

I'm still struggling to actually get our stuff to communicate (trying to get the electron to read an [electric meter](https://www.accuenergy.com/product/acurev-1310-din-rail-three-phase-multifunction-power-energy-meter)), but I'm confident that I'm much closer than I would have otherwise been

**Comment by peergum** [comment]
Glad to help. I wish I had more time to document a bit. I loat quite some time on various problemas from hardware to noise. Feel free to send me any question to phil at peergum.com. I can't guarantee a quick response since I'm on the road but I'll do my best.
